
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  database: <%= ENV["OTODAVAR_DATABASE_NAME"] %>
  username: <%= ENV["OTODAVAR_DATABASE_USERNAME"] %>
  password: <%= ENV["OTODAVAR_DATABASE_PASSWORD"] %>